#!/usr/bin/env ruby

class WorkspaceCompletion
  def initialize(command)
    @command = command
  end
  
  def matches
    projects.select do |task|
      task[0, typed.length] == typed
    end
  end
  
  def typed
    @command[/\s(.+?)$/, 1] || ''
  end
  
  def projects
    `ls $HOME/Workspace/telvue`.split
  end
end

puts WorkspaceCompletion.new(ENV["COMP_LINE"]).matches
exit 0
